# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee29c6f2690587d2aec48b8e2f74db55361a05e5d3b3ce8b960fc923fae905018f4ae7a7685b233f3d3f1130f1dc1c99e053ea6232a309ad4ed184e9a5f2ab05

test:
  secret_key_base: 91ff23cd5f8f14fb23273e64b9f3fab260a433a2f6df7471e9a9aa3d199c89f0c3fc27b4b6facd996cb2a541f3199f46da435caad2799e82ca185ed1b4fb8169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= token_file = Rails.root.join "gitignore/token_file"; if File.exist? token_file then File.read(token_file).chomp else token = SecureRandom.hex(64); File.write(token_file, token); token end %>